import Head from "next/head";
import Image from "next/image";
import LeftNav from "../components/LeftNav/LeftNav";
import Navbar from "../components/Navbar/Navbar";
import Page from "../components/Page/Page";
import RightNav from "../components/RightNav/RightNav";
import styles from "../styles/Home.module.css";
import HomePage from "../components/HomePage/HomePage";
import AboutMe from "../components/AboutMe/AboutMe";
import GetInTouch from "../components/GetInTouch/GetInTouch";
import Project from "../components/Project/Project";
import { createRef, useEffect, useState } from "react";
import SideNavbar from "../components/SideNavbar/SideNavbar";

export default function Home(props) {
  const [navbarState, setNavbarState] = useState([
    { name: "About Me", link: "#aboutme", active: false },
    { name: "Experience", link: "#experience", active: false },
    { name: "Projects", link: "#projects", active: false },
    { name: "Contact Me", link: "#contacts", active: false },
  ]);
  const ref = createRef();
  const [isOnTop, setIsOnTop] = useState(true);
  useEffect(() => {
    if (ref.current) {
      ref.current.addEventListener("scroll", function (e) {
        if (e.target.scrollTop > 65) {
          setIsOnTop(false);
        } else {
          setIsOnTop(true);
        }
      });
    }
  }, [ref]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Shreesh&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main
        ref={ref}
        className={styles.main}
        style={{
          // scrollSnapType: "y mandatory",
          overflowY: "scroll",
          height: "100vh",
          position: "relative",
          scrollBehavior: "smooth",
        }}
      >
        {isOnTop ? (
          <Navbar
            navbarState={navbarState}
            setNavbarState={setNavbarState}
          ></Navbar>
        ) : (
          <SideNavbar
            navbarState={navbarState}
            setNavbarState={setNavbarState}
          ></SideNavbar>
        )}
        <LeftNav></LeftNav>
        <RightNav></RightNav>
        <Page>
          <HomePage></HomePage>
        </Page>
        <Page
          style={{
            justifyContent: "space-evenly",
          }}
        >
          <AboutMe
            navbarState={navbarState}
            setNavbarState={setNavbarState}
          ></AboutMe>
        </Page>

        <Page
          style={{
            height: "fit-content",
            margin: "20px 0px",
          }}
        >
          <Project
            navbarState={navbarState}
            setNavbarState={setNavbarState}
          ></Project>
        </Page>
        {/* {props.isWondowSize ? ( */}
        <Page
          style={{
            backgroundColor: "black",
            color: "white",
          }}
        >
          <GetInTouch
            navbarState={navbarState}
            setNavbarState={setNavbarState}
          ></GetInTouch>
        </Page>
        {/* )  */}
        {/* : null} */}
      </main>
    </div>
  );
}
