import Head from "next/head";
import Image from "next/image";
import LeftNav from "../components/LeftNav/LeftNav";
import Navbar from "../components/Navbar/Navbar";
import Page from "../components/Page/Page";
import RightNav from "../components/RightNav/RightNav";
import styles from "../styles/Home.module.css";
import HomePage from "../components/HomePage/HomePage";
import AboutMe from "../components/AboutMe/AboutMe";
import GetInTouch from "../components/GetInTouch/GetInTouch";
import Project from "../components/Project/Project";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shreesh&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main
        className={styles.main}
        style={{
          scrollSnapType: "y mandatory",
          overflowY: "scroll",
          height: "100vh",
          position: "relative",
          scrollBehavior: "smooth",
        }}
      >
        <Navbar></Navbar>
        <LeftNav></LeftNav>
        <RightNav></RightNav>
        <Page>
          <HomePage></HomePage>
        </Page>
        <Page
          style={{
            justifyContent: "space-evenly",
          }}
        >
          <AboutMe></AboutMe>
        </Page>

        <Page
          style={{
            height: "fit-content",
            margin: "20px 0px",
          }}
        >
          <Project></Project>
        </Page>
        <Page
          style={{
            backgroundColor: "black",
            color: "white",
          }}
        >
          <GetInTouch></GetInTouch>
        </Page>
      </main>
    </div>
  );
}
